export const ADD_REMINDER= 'ADD_REMINDER';
export const REMINDERS_FAILED = 'REMINDERS_FAILED';
export const ADD_REMINDERS = 'ADD_REMINDERS';

export const FETCH_FORECASTS_REQUEST='FETCH_FORECASTS_REQUEST';
export const FETCH_FORECASTS_SUCCESS='FETCH_FORECASTS_SUCCESS';
export const FETCH_FORECASTS_FAILURE='FETCH_FORECASTS_FAILURE';
