export const ADD_REMINDER= 'ADD_REMINDER';
export const REMINDERS_FAILED = 'REMINDERS_FAILED';
export const ADD_REMINDERS = 'ADD_REMINDERS';
/*
export const ADD_FORECASTS='ADD_FORECASTS';
export const FORECASTS_FAILED='FORECASTS_FAILED';
export const ADD_FORECAST='ADD_FORECAST';*/
